owner-id = 0
owner-guild-ids = []
system-channel-id = 0
support-server-url = "https://discord.gg" # Replace this with your support server URL

bot-token = ""
database-url = "asyncpg://..." # If it starts with "postgresql://", replace it with "asyncpg://".

[colors]
theme = "#1FCEEC"
green = "#2ECC71"
red = "#E74C3C"
orange = "#E67E22"
blurple = "#5865F2"

[lavalink]
host = ""
port = 0
password = ""
region = ""
secure = false
