FROM ghcr.io/drizzle-team/gateway:latest AS src

FROM oven/bun:alpine
WORKDIR /entry
COPY --from=src /entry .

ENV PORT=8080

ENTRYPOINT ["/bin/sh", "-c", "MASTERPASS=$(awk -F'\"' '/^drizzle-password/{print $2}' /square/config.toml) && export MASTERPASS && exec bun run index.js"]
